diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/app.f   app.f > app.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/bdata.f   bdata.f > bdata.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/cardin.f   cardin.f > cardin.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/cimat1.f   cimat1.f > cimat1.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/ciout.f   ciout.f > ciout.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/cisym.f   cisym.f > cisym.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/degen.f   degen.f > degen.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/dipm.f   dipm.f > dipm.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/ener.f   ener.f > ener.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/excindo.f   excindo.f > excindo.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/excite.f   excite.f > excite.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/exmat.f   exmat.f > exmat.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/filen1.f   filen1.f > filen1.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/filen5.f   filen5.f > filen5.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/filen6.f   filen6.f > filen6.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/geome.f   geome.f > geome.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/getgeo.f   getgeo.f > getgeo.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/gettxt.f   gettxt.f > gettxt.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/guessp.f   guessp.f > guessp.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/guessalan.f   guessalan.f > guessalan.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/hyf.f   hyf.f > hyf.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/init.f   init.f > init.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/input1.f   input1.f > input1.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/input5.f   input5.f > input5.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/input6.f   input6.f > input6.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/intout.f   intout.f > intout.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/iter.f   iter.f > iter.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/main.f   main.f > main.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/matnis.f   matnis.f > matnis.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/movlap.f   movlap.f > movlap.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/mumu.f   mumu.f > mumu.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/muorb.f   muorb.f > muorb.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/peglag.f   peglag.f > peglag.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/pegleg.f   pegleg.f > pegleg.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/peglig.f   peglig.f > peglig.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/peglog.f   peglog.f > peglog.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/qrdiag.f   qrdiag.f > qrdiag.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/reada.f   reada.f > reada.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/readint.f   readint.f > readint.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/rmopac.f   rmopac.f > rmopac.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/scfmat.f   scfmat.f > scfmat.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/scfout.f   scfout.f > scfout.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/scfq.f   scfq.f > scfq.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/selec.f   selec.f > selec.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/theoga.f   theoga.f > theoga.diff
diff -iEZbB --strip-trailing-cr ../../../../ndol-tuti/ndol2011-ecutoff/ucase.f   ucase.f > ucase.diff
