      SUBROUTINE PEGLOG (N,NC,NR,A)
      include 'ndoldim.inc'

* SUBRUTINA DE IMPRESION DE MATRICES SIMETRICAS CUADRADAS EN EV

      COMMON IR,IW,IC,JOB,IERR,NEX,NOCC,ICHGE,NR1,KORD,INSP,IDUMB,
     &       AUI,AUII,AUEV,AUEVI,NO1(NATMAX)
*
       DIMENSION A(N,N)
       NROW = NR
       NCOL = NC
       KITE = 0
20     LOW = KITE + 1
       KITE = KITE + 8
       IF (KITE.GT.NCOL) KITE = NCOL
       WRITE (IW,1000) (I,I=LOW,KITE)
       WRITE (IW,1002)
       DO 30 J=1,NROW
30     WRITE (IW,1001) J,(A(I,J)*AUEVI,I=LOW,KITE)
       IF (KITE.LT.NCOL) GO TO 20
       RETURN
1000   FORMAT (/5X,8I8)
1001   FORMAT (I5,1X,8F8.3)
1002   FORMAT (1X)
       END
