      SUBROUTINE INPUT6 (NA,R,XC,YC,ZC)
      include 'ndoldim.inc'
      
* TRASPASO  DE LAS COORDENADAS ATOMICAS AL ARREGLO PRINCIPAL Y
* ANULACION ULTERIOR DE SUS TERMINOS

      COMMON /A1/ ZNS(107),ZNP(107),ZND(107),ZND2(107),VAR(10),
     &            ANS(107),ANP(107),ANV(107),F2(17),G1(17),EA(107)
     &       /A2/ BE(107,2),U1(107,2),U2(107,2)
     &       /A3/ GE(107,3),UM(107,2)
      COMMON /N11/ NAT(NATMAX)
      COMMON /OPT/ IOPT(30)
      COMMON /ISYM/ IOZ,NNXY,ICEN(NATMAX),
     .              NRXY,ICEN1(NATMAX),NRYZ,ICEN2(NATMAX)
      COMMON /ARR/ AR(3*NATMAX)
      COMMON IR,IW,IC,JOB,IERR,NEX,NOCC,ICHGE,NR,KORD,INSP,IDUMB,
     &       AUI,AUII,AUEV,AUEVI,NO1(NATMAX)

      DIMENSION R(NA,NA),XC(NA),YC(NA),ZC(NA)

* RECUPERACION DE LAS COORDENADAS CARTESIANAS

      XC(1) = AR(1)
      YC(1) = AR(NATMAX+1)
      ZC(1) = AR(2*NATMAX+1)
      DO 80 I=2,NA
        XC(I) = AR(I)
        YC(I) = AR(NATMAX+I)
        ZC(I) = AR(2*NATMAX+I)
        DO 80 J=1,I-1
          R(I,J) =
     &      SQRT((XC(J)-XC(I))**2+(YC(J)-YC(I))**2+(ZC(J)-ZC(I))**2)
          R(J,I) = R(I,J)
80        CONTINUE

* PREPARACION EVENTUAL FICHERO DEL MAPA DE ISOLINEAS

      IF (IOPT(18).NE.0) THEN
        WRITE (9) NA
        WRITE (9) (XC(I)*AUI,YC(I)*AUI,ZC(I)*AUI,NAT(I),I=1,NA)
      ENDIF

* ESCRITURA EVENTUAL DE LA MATRIZ DE DISTANCIAS INTERATOMICAS

      iselec = 1
      CALL SELEC (IOPT(17),iselec,QQ)
      IF (QQ) THEN
         WRITE (IW,1116)
         CALL PEGLEG (NA,R)
      ENDIF
      RETURN

1116  FORMAT (//' INTERATOMIC DISTANCE MATRIX R(NA,NA)')

      END
