fromdos < app.f   >  unix/app.f
fromdos < bdata.f   >  unix/bdata.f
fromdos < cardin.f   >  unix/cardin.f
fromdos < cimat1.f   >  unix/cimat1.f
fromdos < ciout.f   >  unix/ciout.f
fromdos < cisym.f   >  unix/cisym.f
fromdos < degen.f   >  unix/degen.f
fromdos < dipm.f   >  unix/dipm.f
fromdos < ener.f   >  unix/ener.f
fromdos < excindo.f   >  unix/excindo.f
fromdos < excite.f   >  unix/excite.f
fromdos < exmat.f   >  unix/exmat.f
fromdos < filen1.f   >  unix/filen1.f
fromdos < filen5.f   >  unix/filen5.f
fromdos < filen6.f   >  unix/filen6.f
fromdos < geome.f   >  unix/geome.f
fromdos < getgeo.f   >  unix/getgeo.f
fromdos < gettxt.f   >  unix/gettxt.f
fromdos < guessp.f   >  unix/guessp.f
fromdos < guessalan.f   >  unix/guessalan.f
fromdos < hyf.f   >  unix/hyf.f
fromdos < init.f   >  unix/init.f
fromdos < input1.f   >  unix/input1.f
fromdos < input5.f   >  unix/input5.f
fromdos < input6.f   >  unix/input6.f
fromdos < intout.f   >  unix/intout.f
fromdos < iter.f   >  unix/iter.f
fromdos < main.f   >  unix/main.f
fromdos < matnis.f   >  unix/matnis.f
fromdos < movlap.f   >  unix/movlap.f
fromdos < mumu.f   >  unix/mumu.f
fromdos < muorb.f   >  unix/muorb.f
fromdos < peglag.f   >  unix/peglag.f
fromdos < pegleg.f   >  unix/pegleg.f
fromdos < peglig.f   >  unix/peglig.f
fromdos < peglog.f   >  unix/peglog.f
fromdos < qrdiag.f   >  unix/qrdiag.f
fromdos < reada.f   >  unix/reada.f
fromdos < readint.f   >  unix/readint.f
fromdos < rmopac.f   >  unix/rmopac.f
fromdos < scfmat.f   >  unix/scfmat.f
fromdos < scfout.f   >  unix/scfout.f
fromdos < scfq.f   >  unix/scfq.f
fromdos < selec.f   >  unix/selec.f
fromdos < theoga.f   >  unix/theoga.f
fromdos < ucase.f   >  unix/ucase.f
